version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: spa_postgres
    environment:
      POSTGRES_DB: shift_db
      POSTGRES_USER: spa_user
      POSTGRES_PASSWORD: spa_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - spa_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: spa_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - spa_network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Node.js バックエンドサーバー
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: spa_backend
    ports:
      - "3001:3001"
      - "3002:3002"  # SSE Server
    environment:
      NODE_ENV: development
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: shift_db
      POSTGRES_USER: spa_user
      POSTGRES_PASSWORD: spa_password
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    networks:
      - spa_network
    restart: unless-stopped
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules

volumes:
  postgres_data:
  redis_data:

networks:
  spa_network:
    driver: bridge